# bitbucket-pipelines.yml
pipelines:
  default:
    - step:
        name: No specific pipeline defined for this branch
        script:
          - echo "No specific pipeline defined for this branch. No actions taken."
          - true

  branches:
    main:
      - step:
          name: Sincronizar Bitbucket a GitHub (Main Branch)
          image: atlassian/default-image:latest
          script:
            - git config user.name "Bitbucket Pipelines Bot"
            - git config user.email "pipelines-bot@bitbucket.org"
            - GH_REPO_URL="https://oauth2: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@github.com/VictorZRC/wp-eia.git"
            - git remote add github-mirror $GH_REPO_URL
            - git push github-mirror --all --force
            - git push github-mirror --tags --force

    feature/documents: # <-- ¡Aquí agregamos tu rama específica!
      - step:
          name: Sincronizar Bitbucket a GitHub (Feature Documents Branch)
          image: atlassian/default-image:latest
          script:
            - git config user.name "Bitbucket Pipelines Bot"
            - git config user.email "pipelines-bot@bitbucket.org"
            - GH_REPO_URL="https://oauth2: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@github.com/VictorZRC/wp-eia.git"
            - git remote add github-mirror $GH_REPO_URL
            - git push github-mirror $BITBUCKET_BRANCH --force
            - git push github-mirror --tags --force

    feature/images: # <-- ¡Aquí agregamos tu rama específica!
      - step:
          name: Sincronizar Bitbucket a GitHub (Feature Images Branch)
          image: atlassian/default-image:latest
          script:
            - git config user.name "Bitbucket Pipelines Bot"
            - git config user.email "pipelines-bot@bitbucket.org"
            - GH_REPO_URL="https://oauth2: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@github.com/VictorZRC/wp-eia.git"
            - git remote add github-mirror $GH_REPO_URL
            - git push github-mirror $BITBUCKET_BRANCH --force
            - git push github-mirror --tags --force

    '*': # Este comodín ahora solo capturará ramas que no sean 'main' ni 'feature/documents'
      - step:
          name: Sincronizar Bitbucket a GitHub (Cualquier Otra Rama No Especificada)
          image: atlassian/default-image:latest
          script:
            - git config user.name "Bitbucket Pipelines Bot"
            - git config user.email "pipelines-bot@bitbucket.org"
            - GH_REPO_URL="https://oauth2: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@github.com/VictorZRC/wp-eia.git"
            - git remote add github-mirror $GH_REPO_URL
            - git push github-mirror $BITBUCKET_BRANCH --force
            - git push github-mirror --tags --force